name: campusync
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.8.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_storage: ^12.4.9
  cloud_firestore: ^5.6.11
  google_sign_in: ^6.1.5
  flutter_svg: ^1.1.6
  image_picker: ^0.8.5+3
  intl: ^0.19.0
  provider: ^6.1.1
  http: ^1.4.0
  device_preview: ^1.1.0
  flutter_staggered_grid_view: ^0.6.2
  transparent_image: ^2.0.0
  uuid: ^3.0.6
  firebase_messaging: ^15.2.9
  google_fonts: ^4.0.4
  cached_network_image: ^3.3.1
  curved_navigation_bar: ^1.0.3


  
  # New dependency for image cropping
  image_cropper: ^9.1.0
  image: ^4.0.17
  collection: ^1.17.1
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/profile_pic.png
    - assets/google_icon.png
    - assets/universities.json
    - assets/prodi.json
    - assets/hobbies.json
    - assets/icons/
    - assets/syc.png
 
flutter_launcher_icons:
  android: true
  image_path: "assets/app_icon.png"
